### ISSUE TITLE
there's something wrong with the delete function

### ISSUE THREAD

**Issue by mengfeixiang** [ColdTrick/site_announcements#2]
Thanks for your plugin, I am using the version elgg_18. when I want to delete the site announcement I created, I have to try more than once. sometimes I even can't delete it. Tested on Chrome, Firefox and IE. I think the delete function should be pay attention and  make better. Looking forward to your reply, thanks! My email: lzc90123@gmail.com

**Comment by jdalsem** [comment]
We have no issues with the elgg_18 branch. Besides that, it is not really released, so i advice to update to the latest Elgg 1.9 version and see if that works ok
